### ISSUE TITLE
[Enhancement] Support for various AI models

### ISSUE THREAD

**Issue by Barry-Xu-2018** [fujitatomoya/ros2ai#21]
The current implementation is based on the OpenAI API. Considering that the OpenAI API cannot be used in China, it may not be very convenient to add support for new AI services. Could we consider abstracting the AI interface to make it easier to support different AI APIs?

Furthermore, I have noticed that using other AIs (e.g. [ERNIE-Bot-turbo](https://en.wikipedia.org/wiki/Ernie_Bot)) may not simply return executable commands (always including additional explanations or description. Maybe, It's possible that my prompts may not be accurate enough.). So, each AI should also have a 'filter' function to extract command strings from the information returned by the AI.

**Comment by fujitatomoya** [comment]
@Barry-Xu-2018 thanks for posting issue.

> Considering that the OpenAI API cannot be used in China

besides with this situation,

Expanding ros2ai to other AI service would be really interesting and that is actually already one of my scope described in here, https://raw.githack.com/fujitatomoya/ros2ai/rolling/doc/overview.html.

but at this moment, i would like to go with OpenAI for more user experience 1st.

> So, each AI should also have a 'filter' function to extract command strings from the information returned by the AI.

yeah, that is one of my thought too, we could hook the filtering function in `ros2 ai exec` command.
